---
name: Helm Full Build
description: Helm Full Build composite action multisteps
author: ixxeL
inputs:
  # general
  workingdir:
    description: directory in which to find the Dockerfile
    required: false
    default: .
  values-file:
    description: name of the values.yaml file
    required: false
    default: values.yaml
  # lint
  strict:
    description: use strict mode
    required: false
    default: true
  # datree
  datree-offline:
    description: using offline feature of datree
    required: false
    default: false
  kube-schema-version:
    description: kubernetes apiversion
    required: false
    default: 1.25.0
  # checkov
  artefact:
    description: Name of the file or directory to scan
    required: true
  compact:
    required: false
    default: true
  quiet:
    required: false
    default: false
  skip-download:
    required: false
    default: false
  format:
    required: false
    default: cli
  soft-fail:
    required: false
    default: true
  gate:
    required: false
    default: '50'
  skip-path:
    required: false
  skip-framework:
    description: Filter scan to skip specific infrastructure as code frameworks
    required: false
  skip-check:
    description: Each item may be either a Checkov check ID (CKV_AWS_123), a BC check ID (BC_AWS_GENERAL_123), or a severity (LOW, MEDIUM, HIGH, CRITICAL)
    required: false
  check:
    description: Each item may be either a Checkov check ID (CKV_AWS_123), a BC check ID (BC_AWS_GENERAL_123), or a severity (LOW, MEDIUM, HIGH, CRITICAL)
    required: false
  framework:
    description: Filter scan to run only on specific infrastructure code frameworks
    required: false
  # unittest
  # strict:
  #   description: use strict mode
  #   required: false
  #   default: true
  # values-file:
  #   description: name of the values.yaml file
  #   required: false
  #   default: values.yaml
  with-subchart:
    description: include subchart
    required: false
    default: true
  tests-dir:
    description: tests directory relative to workingdir
    required: false
    default: tests/*.yaml
  # template
  chart-name:
    description: name of the chart
    required: false
  # values-file:
  #   description: name of the values.yaml file
  #   required: false
  #   default: values.yaml
  add-repo:
    description: weither or not to add a repo
    required: false
    default: false
  repo-url:
    description: url of the helm repo to add
    required: false
  repo-name:
    description: name of the helm repo to add
    required: false
    default: temp-repo
  repo-user:
    description: user of the helm repo to add
    required: false
  repo-pwd:
    description: password of the helm repo to add
    required: false
  set:
    description: argument to pass to helm chart as --set command
    required: false
  stdout-mode:
    description: output template to stdout
    required: false
    default: true
  display-mode:
    description: display template result to stdout
    required: false
    default: true
  output-dir:
    description: output directory name for template file
    required: false
    default: helm-tpl-result
  output-file:
    description: output file name for template file
    required: false
    default: result.yaml
outputs:
  CHART_NAME:
    description: chart name
    value: ${{ steps.helm-lint.outputs.CHART_NAME }}
  CHART_VERSION:
    description: chart version
    value: ${{ steps.helm-lint.outputs.CHART_VERSION }}
  CHART_APP_VERSION:
    description: chart appVersion
    value: ${{ steps.helm-lint.outputs.CHART_APP_VERSION }}

runs:
  using: composite
  steps:
  - name: Clone code
    id: clone
    uses: actions/checkout@v3
  - name: Helm linting
    id: helm-lint
    uses: ixxeL-actions/workflows/.github/actions/helm-lint@main
    with:
      workingdir: ${{ inputs.workingdir }}
  - name: Helm Datree scan
    id: helm-datree
    continue-on-error: true
    uses: ixxeL-actions/workflows/.github/actions/helm-datree@main
    with:
      workingdir: ${{ inputs.workingdir }}
  - name: Checkov Helm scan
    id: helm-checkov
    uses: ixxeL-actions/workflows/.github/actions/checkov@main
    with:
      workingdir: ${{ inputs.workingdir }}
      artefact: ${{ inputs.artefact }}
      compact: ${{ inputs.compact }}
      quiet: ${{ inputs.quiet }}
      skip-download: ${{ inputs.skip-download }}
      format: ${{ inputs.format }}
      soft-fail: ${{ inputs.soft-fail }}
      gate: ${{ inputs.gate }}
      skip-path: ${{ inputs.skip-path }}
      skip-framework: ${{ inputs.skip-framework }}
      skip-check: ${{ inputs.skip-check }}
      check: ${{ inputs.check }}
      framework: ${{ inputs.framework }}
  - name: Helm unit testing
    id: helm-unittest
    uses: ixxeL-actions/workflows/.github/actions/helm-unittest@main
    with:
      workingdir: ${{ inputs.workingdir }}
      with-subchart: ${{ inputs.with-subchart }}
      tests-dir: ${{ inputs.tests-dir }}
  - name: Helm templating
    id: helm-template
    uses: ixxeL-actions/workflows/.github/actions/helm-template@main
    with:
      workingdir: ${{ inputs.workingdir }}
      strict: ${{ inputs.strict }}
      chart-name: ${{ inputs.chart-name }}
      values-file: ${{ inputs.values-file }}
      add-repo: ${{ inputs.add-repo }}
      repo-url: ${{ inputs.repo-url }}
      repo-name: ${{ inputs.repo-name }}
      repo-user: ${{ inputs.repo-user }}
      repo-pwd: ${{ inputs.repo-pwd }}
      set: ${{ inputs.set }}
      stdout-mode: ${{ inputs.stdout-mode }}
      display-mode: ${{ inputs.display-mode }}
      output-dir: ${{ inputs.output-dir }}
      output-file: ${{ inputs.output-file }}
  # - name: Helm Packaging
  #   id: helm-package
  #   uses: ixxeL-actions/workflows/.github/actions/helm-package@main
  #   with:
  #     workingdir: ${{ inputs.workingdir }}
  #     chart-name: ${{ needs.helm-lint.outputs.chart-name }}
  #     chart-version: ${{ needs.helm-lint.outputs.chart-version }}
  #     chart-appversion: ${{ needs.helm-lint.outputs.chart-appversion }}
  #     values-file: ${{ inputs.values-file }}
