---
name: Github release
description: Releasing on Github
author: fspiers
inputs:
  tag:
    required: true
  verify-tag:
    required: false
    default: false
  target-branch:
    required: false
    default: main

runs:
  using: composite
  steps:
  - id: gh-release
    run: |
      echo -e "${BLUE}[ STEP - RELEASE GH ] > Releasing on Github${BLANK}"
      echo -e "${CYAN}[ INFO ] > gh version.${BLANK}"
      gh --version

      echo -e "${YELLOW}[ EXECUTING ] > Releasing on tag ${{ inputs.tag }}${BLANK}"
      gh release create ${{ inputs.tag }} --generate-notes --latest --verify-tag=${{ inputs.verify-tag }} --target=${{ inputs.target-branch }}
    shell: bash
    env:
      RED: \033[1;31m
      GREEN: \033[1;32m
      YELLOW: \033[1;33m
      BLUE: \033[1;34m
      PURPLE: \033[1;35m
      CYAN: \033[1;36m
      BLANK: \033[0m