---
name: Check GH Actions templates
on:
  workflow_call:
    inputs:
      extra_args:
        description: options to pass to pre-commit run
        required: false
        default: "--all-files"
        type: string
      ci-image:
        description: Docker image used for CI jobs
        required: false
        default: ixxel/toolbox:ci-latest
        type: string
      shellcheck-severity:
        description: Severity for shellcheck scan
        required: false
        default: warning
        type: string
      shellcheck-path:
        description: Path for shellcheck to analyze
        required: false
        default: .github/
        type: string
      shellcheck-exclude:
        description: Path to exclude for shellcheck
        required: false
        default: .github/workflows/*
        type: string

jobs:
  check-gha-templates:
    name: Check GHA templates
    runs-on: ubuntu-latest
    timeout-minutes: 15
    container:
      image: ${{ inputs.ci-image }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: ~/.cache/pre-commit
          key: pre-commit-3|/usr/bin/python3|${{ hashFiles('.pre-commit-config.yaml') }}
      - run: |
          pwd
          ls -la
          pre-commit run --show-diff-on-failure --color=always ${{ inputs.extra_args }}
        shell: bash
      - name: Shellcheck GHA
        id: shellcheck-gha
        uses: ixxeL-actions/workflows/.github/actions/shellcheck-gha@main
        with:
          path: ${{ inputs.shellcheck-path }}
          exclude: ${{ inputs.shellcheck-exclude }}
          severity: ${{ inputs.shellcheck-severity }}
