---
name: Auto tag workflows
on:
  workflow_dispatch:
    inputs:
      increment:
        required: true
        type: choice
        options:
        - "fix"
        - "minor"
        - "major"
        default: "fix"
        description: Kind of version bump
      # new-ref:
      #   required: true
      #   type: string

jobs:
  auto-tag-repo:
    uses: ixxeL-actions/workflows/.github/workflows/auto-tag.yaml@main
    with:
      # new-ref: ${{ inputs.new-ref }}
      increment: ${{ inputs.increment }}
      git-workdir: .github
    secrets:
      git-token: ${{ secrets.PAT }}