---
name: Auto tag workflows
on:
  workflow_dispatch:
    inputs:
      new-ref:
        required: true
        type: string

jobs:
  retag-img:
    uses: ixxeL-actions/workflows/.github/workflows/auto-tag@main
    with:
      new-ref: ${{ inputs.new-ref }}
    secrets: inherit