---
name: Auto tag workflows
on:
  push:
    branches:
      - main
    paths:
      - .github/**
jobs:
  auto-tag-repo:
    uses: ixxeL-actions/workflows/.github/workflows/__auto-tag__.yaml@v1.3.5
    with:
      git-workdir: .github
    secrets:
      git-token: ${{ secrets.PAT }}
