---
name: Auto tag workflows
on:
  workflow_dispatch:
    inputs:
      new-ref:
        required: true
        type: string

jobs:
  retag-img:
    uses: ixxeL-actions/workflows/.github/workflows/auto-tag.yaml@main
    with:
      new-ref: ${{ inputs.new-ref }}
      git-workdir: .github
    secrets:
      git-token: ${{ secrets.PAT }}