---
name: Auto tag workflows
on:
  workflow_dispatch:
    inputs:
      increment:
        required: true
        type: choice
        options:
          - "fix"
          - "minor"
          - "major"
        default: "fix"
        description: Kind of version bump
jobs:
  auto-tag-repo:
    uses: ixxeL-actions/workflows/.github/workflows/__auto-tag__.yaml@v1.2.0
    with:
      increment: ${{ inputs.increment }}
      git-workdir: .github
    secrets:
      git-token: ${{ secrets.PAT }}
