---
name: Image build
on:
  workflow_call:
    inputs:
      checkov-output-format:
        required: false
        type: string
        # default: cli
      checkov-dir:
        required: false
        type: string
        # default: .
      img-name:
        required: true
        type: string
      tag:
        required: true
        type: string
      github-api-rest-token:
        required: false
        type: string
      github-api-auth:
        required: false
        type: string
        default: 'false'
  workflow_dispatch:

# env:
#   CHECKOV_OUTPUT_FORMAT: ${{ inputs.checkov-output-format }}
#   CHECKOV_DIR: ${{ inputs.checkov-dir }}

jobs:
  prepare:
    name: Prepare
    runs-on: ubuntu-20.04
    container:
      image: ixxel/cd-toolbox:latest
    steps:
    - name: Clone code
      uses: actions/checkout@v3
    # - name: Checkov GitHub Action
    #   uses: bridgecrewio/checkov-action@v12
    #   with:
    #     directory: ${{ inputs.checkov-dir }}
    #     output_format: ${{ inputs.checkov-output-format }}
    - name: Kaniko build
      uses: ixxeL-actions/actions/kaniko@main
      with:
        img-name: ${{ inputs.img-name }}
        tag: ${{ inputs.tag }}
        github-api-rest-token: ${{ inputs.github-api-rest-token }}
        github-api-auth: ${{ inputs.github-api-auth }}

