---
name: Image build
on:
  workflow_call:
    inputs:
      checkov-output-format:
        required: false
        type: string
        default: cli
      checkov-dir:
        required: false
        type: string
        default: .
  workflow_dispatch:

env:
  CHECKOV_OUTPUT_FORMAT: ${{ inputs.checkov-output-format }}
  CHECKOV_DIR: ${{ inputs.checkov-dir }}

jobs:
  prepare:
    name: Prepare
    runs-on: ubuntu-20.04
    container:
      image: ixxel/cd-toolbox:latest
    steps:
    - name: Clone code
      uses: actions/checkout@v3
    - name: Checkov GitHub Action
      uses: bridgecrewio/checkov-action@v12
      with:
        directory: ${CHECKOV_DIR}
        output_format: ${CHECKOV_OUTPUT_FORMAT}

