---
name: Custom Image Builder CI
on:
  workflow_call:
    inputs:
    # General
      workingdir:
        required: false
        default: .
        type: string
    # Checkov
      artefact:
        required: true
        type: string
      compact:
        required: false
        default: true
        type: string
      quiet:
        required: false
        default: false
        type: string
      no-guide:
        required: false
        default: false
        type: string
      format:
        required: false
        default: cli
        type: string
      threshold:
        required: false
        default: critical
        type: string
      soft-fail:
        required: false
        default: true
        type: string
      gate:
        required: false
        default: '50'
        type: string
      # Kaniko
      img-name:
        required: true
        type: string
      tag:
        required: true
        type: string
      github-api-rest-token:
        required: false
        type: string
      github-api-auth:
        required: false
        default: false
        type: boolean
      file:
        required: false
        default: ./Dockerfile
        type: string
      build-arg:
        required: false
        type: string
      target-dir:
        required: false
        default: test
        type: string
      single-snapshot:
        required: false
        default: false
        type: boolean
      new-run:
        required: false
        default: true
        type: boolean
      skip-unused-stages:
        required: false
        default: true
        type: boolean
      snapshot-mode:
        required: false
        default: full
        type: string
      no-push:
        required: false
        default: true
        type: boolean
      verbosity:
        required: false
        default: info
        type: string
      compressed-caching:
        required: false
        default: true
        type: boolean
      # Grype
      image-ref:
        description: image reference
        required: true
        type: string
      transport:
        description: transport type for destination (docker,docker-archive,oci-dir,oci-archive,dir,sbom,registry)
        required: false
        default: docker-archive
        type: string
      fail-on:
        description: set the return code to 1 if a vulnerability is found with a severity >= the given severity
        required: false
        default: critical
        type: string
      output:
        description: report output formatter, formats=[json table cyclonedx template]
        required: false
        default: table
        type: string
      scope:
        description: selection of layers to analyze, options=[Squashed AllLayers]
        required: false
        default: Squashed
        type: string
      template:
        description: specify the path to a Go template file (requires template output to be selected)
        required: false
        default: '""'
        type: string
      verbose:
        description: increase verbosity (-v = info, -vv = debug)
        required: false
        default: ''
        type: string

  workflow_dispatch:

jobs:
  prepare:
    name: Prepare
    timeout-minutes: 10
    runs-on: ubuntu-20.04
    container:
      image: ixxel/ci-toolbox:latest
    steps:
    - name: Clone code
      uses: actions/checkout@v3
    - name: Checkov scan
      uses: ixxeL-actions/workflows/.github/actions/checkov@main
      with:
        workingdir: ${{ inputs.workingdir }}
        artefact: ${{ inputs.artefact }}
        compact: ${{ inputs.compact }}
        quiet: ${{ inputs.quiet }}
        no-guide: ${{ inputs.no-guide }}
        format: ${{ inputs.format }}
        threshold: ${{ inputs.threshold }}
        soft-fail: ${{ inputs.soft-fail }}
        gate: ${{ inputs.gate }}
  build:
    name: Build
    timeout-minutes: 15
    runs-on: ubuntu-20.04
    container:
      image: ixxel/cd-toolbox:latest
    steps:
    - name: Clone code
      id: clone
      uses: actions/checkout@v3
    - name: Set version
      id: set-version
      uses: ixxeL-actions/workflows/.github/actions/set-version@main
    - name: Kaniko build
      id: kaniko-build
      uses: ixxeL-actions/workflows/.github/actions/kaniko@main
      with:
        workingdir: ${{ inputs.workingdir }}
        img-name: ${{ inputs.img-name }}
        tag: ${{ steps.set-version.outputs.PROJECT_VERSION }}
        github-api-rest-token: ${{ inputs.github-api-rest-token }}
        github-api-auth: ${{ inputs.github-api-auth }}
        file: ${{ inputs.file }}
        build-arg: ${{ inputs.build-arg }}
        target-dir: ${{ inputs.target-dir }}
        single-snapshot: ${{ inputs.single-snapshot }}
        new-run: ${{ inputs.new-run }}
        skip-unused-stages: ${{ inputs.skip-unused-stages }}
        snapshot-mode: ${{ inputs.snapshot-mode }}
        no-push: ${{ inputs.no-push }}
        verbosity: ${{ inputs.verbosity }}
        compressed-caching: ${{ inputs.compressed-caching }}
    - name: Grype scan
      id: grype-scan
      uses: ixxeL-actions/workflows/.github/actions/grype@main
      with:
        image-ref: ${{ inputs.target-dir }}/${{ inputs.img-name }}.tar
        transport: ${{ inputs.transport }}
        fail-on: ${{ inputs.fail-on }}
        output: ${{ inputs.output }}
        scope: ${{ inputs.scope }}
        template: ${{ inputs.template }}
        verbose: ${{ inputs.verbose }}
