---
name: Custom Image Builder CI
on:
  workflow_call:
    inputs:
    # General
      workingdir:
        required: false
        default: .
        type: string
    # Checkov
      artefact:
        required: true
        type: string
      # checkov-dir:
      #   required: false
      #   type: string
      #   default: .
      compact:
        required: false
        type: string
      quiet:
        required: false
        type: string
      no-guide:
        required: false
        type: string
      format:
        required: false
        type: string
      threshold:
        required: false
        type: string
      soft-fail:
        required: false
        type: string
      gate:
        required: false
        type: string
      # Kaniko
      img-name:
        required: true
        type: string
      tag:
        required: true
        type: string
      github-api-rest-token:
        required: false
        type: string
      github-api-auth:
        required: false
        type: string
  workflow_dispatch:

jobs:
  prepare:
    name: Prepare
    runs-on: ubuntu-20.04
    container:
      image: ixxel/cd-toolbox:latest
    steps:
    - name: Clone code
      uses: actions/checkout@v3
    # - name: Checkov GitHub Action
    #   uses: bridgecrewio/checkov-action@v12
    #   with:
    #     directory: ${{ inputs.workingdir }}
    #     output_format: ${{ inputs.checkov-output-format }}
    # - name: Checkov scan
    #   uses: ixxeL-actions/workflows/actions/checkov@main
    #   with:
    #     workingdir: ${{ inputs.workingdir}}
    #     artefact: ${{ inputs.artefact}}
    #     compact: ${{ inputs.compact}}
    #     quiet: ${{ inputs.quiet}}
    #     no-guide: ${{ inputs.no-guide}}
    #     format: ${{ inputs.format}}
    #     threshold: ${{ inputs.threshold}}
    #     soft-fail: ${{ inputs.soft-fail}}
    #     gate: ${{ inputs.gate}}
    - name: Kaniko build
      uses: ixxeL-actions/workflows/actions/kaniko@main
      with:
        img-name: ${{ inputs.img-name }}
        tag: ${{ inputs.tag }}
        github-api-rest-token: ${{ inputs.github-api-rest-token }}
        github-api-auth: ${{ inputs.github-api-auth }}

