---
name: Helm chart build
on:
  workflow_dispatch:

  workflow_call:
    inputs:
    # General
      workingdir:
        required: false
        default: .
        type: string
      ci-image:
        description: Docker image used for CI jobs
        required: false
        default: ixxel/ci-toolbox:v1.5.0
        type: string
      template-repo:
        description: repository of the ci/cd template to use
        required: false
        default: ixxeL-actions/workflows/.github/actions
        type: string
      template-ref:
        description: branch or tag of the ci/cd template to use
        required: false
        default: main
        type: string
    # helm unit tests
      with-subcharts:
        description: include subcharts
        required: false
        default: true
        type: boolean
      tests-dir:
        description: tests directory relative to workingdir
        required: false
        default: tests/*.yaml
        type: string
    # helm template
      strict:
        description: use strict mode
        required: false
        default: true
        type: boolean
      chart-name:
        description: name of the chart
        required: false
        type: string
      values-file:
        description: name of the values.yaml file
        required: false
        default: values.yaml
        type: string
      add-repo:
        description: weither or not to add a repo
        required: false
        default: false
        type: boolean
      repo-url:
        description: url of the helm repo to add
        required: false
        type: string
      repo-name:
        description: name of the helm repo to add
        required: false
        default: temp-repo
        type: string
      repo-user:
        description: user of the helm repo to add
        required: false
        type: string
      repo-pwd:
        description: password of the helm repo to add
        required: false
        type: string
      set:
        description: argument to pass to helm chart as --set command
        required: false
        type: string
      stdout-mode:
        description: output template to stdout
        required: false
        default: true
        type: boolean
      display-mode:
        description: display template result to stdout
        required: false
        default: true
        type: boolean
      output-dir:
        description: output directory name for template file
        required: false
        default: helm-tpl-result
        type: string
      output-file:
        description: output file name for template file
        required: false
        default: result.yaml
        type: string

env:
  TPL_REPO: ${{ inputs.template-repo }}
  TPL_REF: ${{ inputs.template-ref }}

jobs:
  helm-lint:
    name: helm-lint
    timeout-minutes: 3
    runs-on: ubuntu-20.04
    container:
      image: ${{ inputs.ci-image }}
    steps:
    - name: Clone code
      uses: actions/checkout@v3
    - name: Helm linting
      uses: $TPL_REPO/helm-lint@$TPL_REF
      with:
        workingdir: ${{ inputs.workingdir }}
  helm-unittest:
    name: helm-unittest
    timeout-minutes: 10
    runs-on: ubuntu-20.04
    container:
      image: ${{ inputs.ci-image }}
    steps:
    - name: Clone code
      uses: actions/checkout@v3
    - name: Helm unit testing
      uses: $TPL_REPO/helm-unittest@$TPL_REF
      with:
        workingdir: ${{ inputs.workingdir }}
        with-subcharts: ${{ inputs.with-subcharts }}
        tests-dir: ${{ inputs.tests-dir }}
  helm-template:
    name: helm-template
    timeout-minutes: 3
    runs-on: ubuntu-20.04
    container:
      image: ${{ inputs.ci-image }}
    steps:
    - name: Clone code
      id: clone
      uses: actions/checkout@v3
    - name: Helm templating
      uses: $TPL_REPO/helm-template@$TPL_REF
      with:
        workingdir: ${{ inputs.workingdir }}
        strict: ${{ inputs.strict }}
        chart-name: ${{ inputs.chart-name }}
        values-file: ${{ inputs.values-file }}
        add-repo: ${{ inputs.add-repo }}
        repo-url: ${{ inputs.repo-url }}
        repo-name: ${{ inputs.repo-name }}
        repo-user: ${{ inputs.repo-user }}
        repo-pwd: ${{ inputs.repo-pwd }}
        set: ${{ inputs.set }}
        stdout-mode: ${{ inputs.stdout-mode }}
        display-mode: ${{ inputs.display-mode }}
        output-dir: ${{ inputs.output-dir }}
        output-file: ${{ inputs.output-file }}
