---
name: Helm chart build
on:
  workflow_dispatch:
  workflow_call:
    inputs:
      # General
      workingdir:
        required: false
        type: string
      runs-on:
        description: OS to run jobs on
        required: false
        default: ubuntu-latest
        type: string
      helm-image:
        description: Docker image used for CI jobs
        required: false
        default: ixxel/toolbox:helm-latest
        type: string
        # Update version
      chart-update:
        required: false
        default: true
        type: boolean
      chart-increment:
        required: false
        default: fix
        type: string
        # helm unit tests
      with-subchart:
        description: include subchart
        required: false
        default: true
        type: boolean
      tests-dir:
        description: tests directory relative to workingdir
        required: false
        default: tests/*.yaml
        type: string
        # Checkov
      artefact:
        required: true
        type: string
      compact:
        required: false
        default: true
        type: string
      quiet:
        required: false
        default: false
        type: string
      skip-download:
        required: false
        default: false
        type: string
      format:
        required: false
        default: cli
        type: string
      soft-fail:
        required: false
        default: true
        type: string
      gate:
        required: false
        default: '0'
        type: string
      skip-path:
        required: false
        type: string
      skip-framework:
        required: false
        type: string
      skip-check:
        required: false
        type: string
      check:
        required: false
        type: string
      framework:
        required: false
        type: string
        # helm template
      strict:
        description: use strict mode
        required: false
        default: true
        type: boolean
      chart-name:
        description: name of the chart
        required: false
        type: string
      values-file:
        description: name of the values.yaml file
        required: false
        default: values.yaml
        type: string
      stdout-mode:
        description: output template to stdout
        required: false
        default: true
        type: boolean
      display-mode:
        description: display template result to stdout
        required: false
        default: true
        type: boolean
      output-dir:
        description: output directory name for template file
        required: false
        default: helm-tpl-result
        type: string
      output-file:
        description: output file name for template file
        required: false
        default: result.yaml
        type: string
      # helm push
      helm-devel:
        required: false
        default: false
        type: boolean
      helm-repo-name:
        required: false
        default: chartmuseum
        type: string
      helm-repo-url:
        required: false
        default: https://whbox-chartmuseum.pp.dktapp.cloud
        type: string
      helm-repo-username:
        required: false
        default: root
        type: string
      helm-force-update:
        required: false
        default: true
        type: boolean
      helm-skip-tls:
        required: false
        default: true
        type: boolean
      helm-push-type:
        required: false
        default: chartmuseum
        type: string
      # git tag/push
      # git-staging-dir:
      #   required: false
      #   default: fullstack
      #   type: string
      push-option:
        required: false
        default: ci.skip
        type: string
      git-workdir:
        required: false
        default: .
        type: string
      # chart update
      evaluate-update:
        required: false
        default: true
        type: boolean
concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true
env:
  COMPONENT_NAME: ${{ inputs.workingdir }}
jobs:
  helm-build:
    name: helm-build
    timeout-minutes: 5
    runs-on: ubuntu-latest
    container:
      image: ${{ inputs.helm-image }}
    steps:
      - name: Clone code
        id: git-clone
        uses: actions/checkout@v1
        with:
          fetch-depth: '0'
      - name: Helm linting
        id: helm-lint
        uses: ixxeL-actions/workflows/.github/actions/helm-lint@v1.1.0
        with:
          workingdir: ${{ inputs.workingdir }}
      - name: Bump version
        id: bump-version
        uses: ixxeL-actions/workflows/.github/actions/bump-version@v1.1.0
        with:
          update: ${{ inputs.chart-update }}
          increment: ${{ inputs.chart-increment }}
          current-version: ${{ steps.helm-lint.outputs.CHART_VERSION }}
      - name: Helm Checkov scan
        id: helm-checkov
        uses: ixxeL-actions/workflows/.github/actions/checkov@v1.1.0
        with:
          workingdir: ${{ inputs.workingdir }}
          artefact: ${{ inputs.artefact }}
          compact: ${{ inputs.compact }}
          quiet: ${{ inputs.quiet }}
          skip-download: ${{ inputs.skip-download }}
          format: ${{ inputs.format }}
          soft-fail: ${{ inputs.soft-fail }}
          gate: ${{ inputs.gate }}
          skip-path: ${{ inputs.skip-path }}
          skip-framework: ${{ inputs.skip-framework }}
          skip-check: ${{ inputs.skip-check }}
          check: ${{ inputs.check }}
          framework: ${{ inputs.framework }}
      - name: Helm Unit testing
        id: helm-unittest
        uses: ixxeL-actions/workflows/.github/actions/helm-unittest@v1.1.0
        with:
          workingdir: ${{ inputs.workingdir }}
          with-subchart: ${{ inputs.with-subchart }}
          tests-dir: ${{ inputs.tests-dir }}
      - name: Helm Templating
        id: helm-template
        uses: ixxeL-actions/workflows/.github/actions/helm-template@v1.1.0
        with:
          workingdir: ${{ inputs.workingdir }}
          strict: ${{ inputs.strict }}
          chart-name: ${{ inputs.chart-name }}
          values-file: ${{ inputs.values-file }}
          set: ${{ inputs.set }}
          stdout-mode: ${{ inputs.stdout-mode }}
          display-mode: ${{ inputs.display-mode }}
          output-dir: ${{ inputs.output-dir }}
          output-file: ${{ inputs.output-file }}
      - name: Helm Packaging
        id: helm-package
        uses: ixxeL-actions/workflows/.github/actions/helm-package@v1.1.0
        with:
          workingdir: ${{ inputs.workingdir }}
          chart-name: ${{ steps.helm-lint.outputs.CHART_NAME }}
          chart-version: ${{ steps.bump-version.outputs.VERSION }}
          chart-appversion: ${{ steps.helm-lint.outputs.CHART_APP_VERSION }}
          values-file: ${{ inputs.values-file }}
      # - name: Helm pushing
      #   id: helm-push
      #   uses: ixxeL-actions/workflows/.github/actions/helm-push@main
      #   with:
      #     workingdir: ${{ inputs.workingdir }}
      #     chart-name: ${{ steps.helm-lint.outputs.CHART_NAME }}
      #     chart-version: ${{ steps.bump-version.outputs.VERSION }}
      #     chart-appversion: ${{ steps.helm-lint.outputs.CHART_APP_VERSION }}
      #     devel: ${{ inputs.helm-devel }}
      #     repo-name: ${{ inputs.helm-repo-name }}
      #     repo-url: ${{ inputs.helm-repo-url }}
      #     repo-username: ${{ inputs.helm-repo-username }}
      #     repo-password: ${{ secrets.CHARTMUSEUM_PASSWORD }}
      #     force-update: ${{ inputs.helm-force-update }}
      #     skip-tls: ${{ inputs.helm-skip-tls }}
      #     push-type: ${{ inputs.helm-push-type }}
      #     pkg-path: ${{ steps.helm-package.outputs.PKG_PATH }}
      - name: Chart update
        id: chart-update
        uses: ixxeL-actions/workflows/.github/actions/chart-update@v1.1.0
        with:
          workingdir: ${{ inputs.workingdir }}
          evaluate-update: ${{ inputs.evaluate-update }}
          promotion-version: ${{ steps.bump-version.outputs.VERSION }}
      - name: Helm docs
        id: helm-docs
        uses: ixxeL-actions/workflows/.github/actions/helm-docs@v1.1.0
        with:
          chart-search-root: ${{ inputs.workingdir }}
      - name: Git config
        id: git-config
        uses: ixxeL-actions/workflows/.github/actions/git-config@v1.1.0
        with:
          git-workdir: ${{ inputs.git-workdir }}
      - name: Git push
        id: git-push
        uses: ixxeL-actions/workflows/.github/actions/git-push@v1.1.0
        with:
          git-token: ${{ secrets.PAT }}
          git-msg: ':package: CI release of helm chart ${{ env.COMPONENT_NAME }} version ${{ steps.bump-version.outputs.VERSION }} from user ${GITHUB_ACTOR} [skip ci]'
          git-workdir: ${{ inputs.git-workdir }}
          git-staging-dir: ${{ inputs.workingdir }}
          push-option: ${{ inputs.push-option }}
      - name: Git tag
        id: git-tag
        uses: ixxeL-actions/workflows/.github/actions/git-tag@v1.1.0
        with:
          tag-msg: ':package: CI release of helm chart ${{ env.COMPONENT_NAME }} version ${{ steps.bump-version.outputs.VERSION }} from user ${GITHUB_ACTOR} [skip ci]'
          tag-value: ${{ steps.bump-version.outputs.VERSION }}
          git-workdir: ${{ inputs.git-workdir }}
          push-option: ${{ inputs.push-option }}
