---
name: Update Pull Request title
on:
  pull_request:
    types:
      - opened
jobs:
  update-pr:
    uses: ixxeL-actions/workflows/.github/workflows/__update-PR-classic__.yaml@v1.4.0
    secrets:
      git-token: ${{ secrets.PAT }}
