---
name: Update Pull Request title
on:
  pull_request:
    types:
      - opened
jobs:
  update-pr:
    uses: ixxeL-actions/workflows/.github/workflows/__update-PR-classic__.yaml@main
    secrets: inherit
