---
name: Update Pull Request title
on:
  pull_request:
    types:
      - opened
jobs:
  update-pr:
    uses: ixxeL-actions/workflows/.github/workflows/__update-PR-classic__.yaml@v2.0.1
    secrets:
      git-token: ${{ secrets.PAT }}
