---
name: Pre-commit check
on:
  pull_request:
    types:
      - opened
      - synchronize
    branches:
      - "main"
jobs:
  update-pr:
    uses: ixxeL-actions/workflows/.github/workflows/__check-gha-templates__.yaml@v1.3.1
